export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const LOGIN_WITH_GOOGLE_TOKEN = 'LOGIN_WITH_GOOGLE_TOKEN';
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const GET_AVATAR = 'GET_AVATAR';
